import "server-only";
import { mkdir, readFile, writeFile, unlink } from "node:fs/promises";
import path from "node:path";

/**
 * Submission storage.
 *
 * Files go to the local filesystem so the project runs anywhere with no cloud
 * account. Swapping this for S3 or Vercel Blob means reimplementing these four
 * functions; nothing above them knows where the bytes live.
 *
 * Two rules that matter more than the storage backend:
 *   * The stored name is generated by us, never taken from the upload. A
 *     client-supplied name is an attacker-supplied path.
 *   * Every read resolves the path and checks it is still inside the upload
 *     directory, so a crafted name cannot escape it.
 */

export const MAX_UPLOAD_BYTES = Number(
  process.env.MAX_UPLOAD_BYTES ?? 10 * 1024 * 1024,
);

function uploadDir() {
  // turbopackIgnore keeps the bundler from tracing the whole project into the
  // server output because this path is only known at runtime. The directory is
  // runtime state, not something to bundle.
  return path.resolve(/* turbopackIgnore: true */ process.env.UPLOAD_DIR ?? "uploads");
}

/** Resolves a stored name to an absolute path, refusing anything that escapes. */
function resolveInside(storedName: string): string {
  const dir = uploadDir();
  const full = path.resolve(dir, storedName);
  const relative = path.relative(dir, full);

  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw new Error("Refusing to touch a file outside the upload directory.");
  }
  return full;
}

export async function saveSubmissionFile(
  storedName: string,
  bytes: Uint8Array,
): Promise<void> {
  await mkdir(uploadDir(), { recursive: true });
  await writeFile(resolveInside(storedName), bytes);
}

export async function readSubmissionFile(storedName: string): Promise<Buffer> {
  return readFile(resolveInside(storedName));
}

/** Best effort: a leftover file is untidy, a failed request is worse. */
export async function deleteSubmissionFile(storedName: string): Promise<void> {
  try {
    await unlink(resolveInside(storedName));
  } catch {
    // Already gone, or never written. Nothing to do.
  }
}
